### ISSUE TITLE
[feat] 커스텀 응답 및 예외 처리, 프로젝트 세팅 수정, API 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [SOPT-all/35-COLLABORATION-SERVER-SAFETYREPORT#7]
## Feature Issue 📌

- 커스텀 응답 및 예외 처리
- 프로젝트 세팅 수정
- 신고 카테고리 설명 GET API 구현
- 갤러리 GET API 구현

환경 구성 및 테스트를 위해 부득이하게 하나의 브랜치에 많은 일을 하게 된 점.. 양해 부탁드립니다🥲🥲

<br>

## Todo ✔️

- [x] 커스텀 응답 및 예외 처리
- [x] 프로젝트 세팅 수정
- [x] 신고 카테고리 설명 GET API 구현
- [x] 갤러리 GET API 구현
